name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build Backend Docker Image
      run: |
        OWNER="${{ github.repository_owner }}"
        docker build -t ghcr.io/${OWNER,,}/svgboard-backend:latest ./backend
    
    - name: Build Frontend Docker Image
      run: |
        OWNER="${{ github.repository_owner }}"
        docker build -t ghcr.io/${OWNER,,}/svgboard-frontend:latest ./frontend
    
    - name: Push Backend Image
      run: |
        OWNER="${{ github.repository_owner }}"
        docker push ghcr.io/${OWNER,,}/svgboard-backend:latest
    
    - name: Push Frontend Image
      run: |
        OWNER="${{ github.repository_owner }}"
        docker push ghcr.io/${OWNER,,}/svgboard-frontend:latest
    
    - name: Test Docker Compose
      run: docker compose config
